
global using MediatR;
global using JobOffer.Application.DTOs;
global using AutoMapper;
global using JobOffer.Core.Lookups;
global using JobOffer.Core.Contracts;
global using JobOffer.Application.Services.Categories.Commands;
global using JobOffer.Application.Services.Categories.Queries;
global using JobOffer.Application.Services.Typies.Commands;
global using JobOffer.Application.Services.Typies.Queries;
global using JobOffer.Application.Services.Cities.Queries;
global using JobOffer.Application.Services.Cities.Commands;
global using JobOffer.Application.Services.Countries.Queries;
global using JobOffer.Application.Services.Countries.Commands;
global using Microsoft.AspNetCore.Http;
global using JobOffer.Application.Services.Account.Commands;
global using JobOffer.Core.Entities;
global using Microsoft.AspNetCore.Identity;
global using JobOffer.Application.Services.CommonHandler;